# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                            💥 #
# 💥 Do not edit this file as it will be overwritten!           💥 #
# 💥                                                            💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #

# locals can not be overwritten, so anything that is really static should be put in here
locals {
  ns_prefix = compact([var.ns_env_name, var.prefix_short])

  ns_name = "${length(local.ns_prefix) > 0 ? "${join(var.ns_seperator, local.ns_prefix)}." : ""}${var.ns_zone_new}"

  account_aliases = [
    "rimu",
    "ritdu-main",
    "ritdu-jobs-af1",
    "roam-horizon-af1",
    "ritdu-dcd",
    "rimu-prop-vnm",
    "ritdu-pe-eu1",
    "ritdu-dcd-eu2",
    "cube-sdc-eu1",
    "ritdu-hex-eu1",
    "ritdu-meta-eu1",
    "ritdu-bi-eu1",
    "ritdu-mkt-eu1",
    "ritdu-ecom-eu1",
    "rmn-imo-eu1",
    "ritdu-vapor-eu1",
    "ritdu-cds-eu1",
    "ritdu-sol-eu1",
    "ritdu-logs-eu1",
    "ritdu-ias-eu1",
    "ritdu-rsmg-eu1",
    "ritdu-rias-mdb-eu1",
  ]

  main_vpc_cidr             = var.vpcs["${var.prefix}.cidr"]
  main_vpc_private_subs     = split(" ", var.vpcs["${var.prefix}.private_subs"])
  main_vpc_database_subs    = split(" ", var.vpcs["${var.prefix}.database_subs"])
  main_vpc_elasticache_subs = var.prefix != "ritdu-rias-mdb-eu1" ? split(" ", var.vpcs["${var.prefix}.elasticache_subs"]) : null
  main_vpc_public_subs      = split(" ", var.vpcs["${var.prefix}.public_subs"])
  main_vpc_region           = var.vpcs["${var.prefix}.region"]
  main_vpc_azs              = split(" ", var.vpcs["${var.prefix}.azs"])
  main_vpc_single_natgw     = var.vpcs["${var.prefix}.single_natgw"]
  main_account_id           = var.vpcs["${var.prefix}.account_id"]

  core_account_id = 135132174985

  bastion_ip      = "172.16.16.16"
  proxy_ip        = "172.16.16.18"
  proxy_ip_public = "54.220.166.15"
  rmn_bastion_ip  = "10.27.16.16"
  rmn_pritunl_ip  = "10.27.16.204"
}
