# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                            💥 #
# 💥 Do not edit this file as it will be overwritten!           💥 #
# 💥                                                            💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #

variable "region" {
  type    = string
  default = "eu-west-1"
}

variable "vpcs" {
  type = map(string)
}

# sports account
variable "cloudflare_account_id_sports" {
  type    = string
  default = "b75621b4c14284e6957e8091d0272db8"
}

variable "cloudflare_email_sports" {
  type    = string
  default = ""
}

variable "cloudflare_token_sports" {
  type    = string
  default = ""
}

# group account
variable "cloudflare_account_id_group" {
  type    = string
  default = "adfa414fd60e0afe8b94b9e8364330af"
}

variable "cloudflare_email_group" {
  type    = string
  default = ""
}

variable "cloudflare_token_group" {
  type    = string
  default = ""
}

# main account
variable "cloudflare_account_id" {
  type    = string
  default = "6178465172ab2960ec0dcdb25cc5bd49"
}

variable "cloudflare_email" {
  type    = string
  default = ""
}

variable "cloudflare_token" {
  type    = string
  default = ""
}

variable "ns_zone_new" {
  type    = string
  default = "ringier.tech"
}

variable "ns_zone_id_new" {
  type    = string
  default = "6b0460da3a4903ccc2b2a2371fe79d26"
}

variable "ns_seperator" {
  type    = string
  default = "-"
}

variable "ns_env_name" {
  type    = string
  default = ""
}

variable "key_pair_public" {
  type = string
}

variable "kubectl_config_path" {
  description = "The path to the config file to use for kubectl. If empty, defaults to $HOME/.kube/config"
  type        = string
  default     = "~/.kube/config"
}


# Imobiliare owns this whole IPV4 block.
variable "imobiliare_ips" {
  type        = list(string)
  description = "List of cidr blocks to be whitelisted"

  default = [
    "89.33.106.0/24",
  ]
}

variable "imobiliare_ips_no_suffix" {
  type        = list(string)
  description = "List of ips to be whitelisted (cf does not accept /32 :pray:)"

  default = [
    "35.156.195.102",
  ]
}

variable "office_ips" {
  type = list(string)

  default = [
    "169.255.147.6/32",
    "108.128.7.94/32"
  ]
}

variable "vpn_private_ips" {
  type = list(string)

  default = [
    "172.16.16.151/32"
  ]
}

variable "home_ips" {
  type = list(string)

  default = [
    # Matthew Nessworthy (gh:matthewnessworthy email:matthewn@ringier.co.za)
    "213.165.170.197/32",
    # Peter Frescura (gh:puzzledvacuum email:peterf@ringier.co.za)
    "165.255.244.123/32",
    # Stephen Perelson (gh:sperelson email:stephenp@ringier.co.za)
    "102.212.97.62/32",
  ]
}

variable "office_ips_no_suffix" {
  type = list(string)

  default = [
    "169.255.147.6",
    "108.128.7.94"
  ]
}

variable "home_ips_no_suffix" {
  type = list(string)

  default = [
    # Matthew Nessworthy (gh:matthewnessworthy email:matthewn@ringier.co.za)
    "213.165.170.197",
    # Peter Frescura (gh:puzzledvacuum email:peterf@ringier.co.za)
    "165.255.244.123",
    # Stephen Perelson (gh:sperelson email:stephenp@ringier.co.za)
    "102.212.97.62",
  ]
}

variable "backup_window" {
  type    = string
  default = "00:00-02:00"
}

variable "maintenance_window" {
  type    = string
  default = "sat:03:00-sat:05:00"
}
