# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                            💥 #
# 💥 Do not edit this file as it will be overwritten!           💥 #
# 💥                                                            💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #





vpcs = {
  # we unfortunately can not mix types, but will be fixed in 0.12 (see: https://github.com/hashicorp/terraform/issues/14322)
  "rimu.cidr"             = "172.16.128.0/19"
  "rimu.single_natgw"     = "false"
  "rimu.private_subs"     = "172.16.128.0/24 172.16.129.0/24 172.16.130.0/24"
  "rimu.database_subs"    = "172.16.133.0/24 172.16.134.0/24 172.16.135.0/24"
  "rimu.elasticache_subs" = "172.16.138.0/24 172.16.139.0/24 172.16.140.0/24"
  "rimu.public_subs"      = "172.16.143.0/24 172.16.144.0/24 172.16.145.0/24"
  "rimu.region"           = "ap-southeast-1"
  "rimu.azs"              = "ap-southeast-1a ap-southeast-1b ap-southeast-1c"
  "rimu.account_id"       = 135132174985
}
