# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                            💥 #
# 💥 Do not edit this file as it will be overwritten!           💥 #
# 💥                                                            💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #





vpcs = {
  # we unfortunately can not mix types, but will be fixed in 0.12 (see: https://github.com/hashicorp/terraform/issues/14322)

  # base/core
  # rimu
  "rimu.cidr"             = "172.16.0.0/19"
  "rimu.single_natgw"     = "false"
  "rimu.private_subs"     = "172.16.0.0/24 172.16.1.0/24 172.16.2.0/24"
  "rimu.database_subs"    = "172.16.5.0/24 172.16.6.0/24 172.16.7.0/24"
  "rimu.elasticache_subs" = "172.16.10.0/24 172.16.11.0/24 172.16.12.0/24"
  "rimu.public_subs"      = "172.16.15.0/24 172.16.16.0/24 172.16.17.0/24"
  "rimu.region"           = "eu-west-1"
  "rimu.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "rimu.account_id"       = "135132174985"

  # payeer account
  # ritdu-main
  "ritdu-main.cidr"             = "10.11.0.0/19"
  "ritdu-main.single_natgw"     = "true"
  "ritdu-main.private_subs"     = "10.11.0.0/24 10.11.1.0/24 10.11.2.0/24"
  "ritdu-main.database_subs"    = "10.11.5.0/24 10.11.6.0/24 10.11.7.0/24"
  "ritdu-main.elasticache_subs" = "10.11.10.0/24 10.11.11.0/24 10.11.19.0/24"
  "ritdu-main.public_subs"      = "10.11.15.0/24 10.11.16.0/24 10.11.17.0/24"
  "ritdu-main.region"           = "eu-west-1"
  "ritdu-main.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-main.account_id"       = "953455652261"

  # jobs
  # ritdu-jobs
  "ritdu-jobs-af1.cidr"             = "10.12.0.0/19"
  "ritdu-jobs-af1.single_natgw"     = "false"
  "ritdu-jobs-af1.private_subs"     = "10.12.0.0/24 10.12.1.0/24 10.12.2.0/24"
  "ritdu-jobs-af1.database_subs"    = "10.12.5.0/24 10.12.6.0/24 10.12.7.0/24"
  "ritdu-jobs-af1.elasticache_subs" = "10.12.10.0/24 10.12.11.0/24 10.12.12.0/24"
  "ritdu-jobs-af1.public_subs"      = "10.12.15.0/24 10.12.16.0/24 10.12.17.0/24"
  "ritdu-jobs-af1.region"           = "eu-west-1"
  "ritdu-jobs-af1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-jobs-af1.account_id"       = "471953789682"

  # sec 1
  # ritdu-sec
  "ritdu-sec-eu1.cidr"             = "10.13.0.0/19"
  "ritdu-sec-eu1.single_natgw"     = "true"
  "ritdu-sec-eu1.private_subs"     = "10.13.0.0/24 10.13.1.0/24 10.13.2.0/24"
  "ritdu-sec-eu1.database_subs"    = "10.13.5.0/24 10.13.6.0/24 10.13.7.0/24"
  "ritdu-sec-eu1.elasticache_subs" = "10.13.10.0/24 10.13.11.0/24 10.13.12.0/24"
  "ritdu-sec-eu1.public_subs"      = "10.13.15.0/24 10.13.16.0/24 10.13.17.0/24"
  "ritdu-sec-eu1.region"           = "eu-west-1"
  "ritdu-sec-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-sec-eu1.account_id"       = "636025426721"

  # horizon
  # roam-horizon
  "roam-horizon-af1.cidr"             = "10.14.0.0/19"
  "roam-horizon-af1.single_natgw"     = "false"
  "roam-horizon-af1.private_subs"     = "10.14.0.0/24 10.14.1.0/24 10.14.2.0/24"
  "roam-horizon-af1.database_subs"    = "10.14.5.0/24 10.14.6.0/24 10.14.7.0/24"
  "roam-horizon-af1.elasticache_subs" = "10.14.10.0/24 10.14.11.0/24 10.14.12.0/24"
  "roam-horizon-af1.public_subs"      = "10.14.15.0/24 10.14.16.0/24 10.14.17.0/24"
  "roam-horizon-af1.region"           = "eu-west-1"
  "roam-horizon-af1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "roam-horizon-af1.account_id"       = "947872912714"

  # bus 1
  # ritdu-dcd
  "ritdu-dcd.cidr"             = "10.15.0.0/19"
  "ritdu-dcd.single_natgw"     = "false"
  "ritdu-dcd.private_subs"     = "10.15.0.0/24 10.15.1.0/24 10.15.2.0/24"
  "ritdu-dcd.database_subs"    = "10.15.5.0/24 10.15.6.0/24 10.15.7.0/24"
  "ritdu-dcd.elasticache_subs" = "10.15.10.0/24 10.15.11.0/24 10.15.12.0/24"
  "ritdu-dcd.public_subs"      = "10.15.15.0/24 10.15.16.0/24 10.15.17.0/24"
  "ritdu-dcd.region"           = "eu-west-1"
  "ritdu-dcd.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-dcd.account_id"       = "634401859868"

  # prop
  # rimu-prop
  "rimu-prop-vnm.cidr"             = "10.16.0.0/19"
  "rimu-prop-vnm.single_natgw"     = "false"
  "rimu-prop-vnm.private_subs"     = "10.16.0.0/24 10.16.1.0/24 10.16.2.0/24"
  "rimu-prop-vnm.database_subs"    = "10.16.5.0/24 10.16.6.0/24 10.16.7.0/24"
  "rimu-prop-vnm.elasticache_subs" = "10.16.10.0/24 10.16.11.0/24 10.16.12.0/24"
  "rimu-prop-vnm.public_subs"      = "10.16.15.0/24 10.16.16.0/24 10.16.17.0/24"
  "rimu-prop-vnm.region"           = "eu-west-1"
  "rimu-prop-vnm.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "rimu-prop-vnm.account_id"       = "348539006591"

  # testing/pe
  # ritdu-pe
  "ritdu-pe-eu1.cidr"             = "10.17.0.0/19"
  "ritdu-pe-eu1.single_natgw"     = "true"
  "ritdu-pe-eu1.private_subs"     = "10.17.0.0/24 10.17.1.0/24 10.17.2.0/24"
  "ritdu-pe-eu1.database_subs"    = "10.17.5.0/24 10.17.6.0/24 10.17.7.0/24"
  "ritdu-pe-eu1.elasticache_subs" = "10.17.10.0/24 10.17.11.0/24 10.17.12.0/24"
  "ritdu-pe-eu1.public_subs"      = "10.17.15.0/24 10.17.16.0/24 10.17.17.0/24"
  "ritdu-pe-eu1.region"           = "eu-west-1"
  "ritdu-pe-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-pe-eu1.account_id"       = "025015820777"

  # bus 2
  # ritdu-dcd
  "ritdu-dcd-eu2.cidr"             = "10.18.0.0/19"
  "ritdu-dcd-eu2.single_natgw"     = "true"
  "ritdu-dcd-eu2.private_subs"     = "10.18.0.0/24 10.18.1.0/24 10.18.2.0/24"
  "ritdu-dcd-eu2.database_subs"    = "10.18.5.0/24 10.18.6.0/24 10.18.7.0/24"
  "ritdu-dcd-eu2.elasticache_subs" = "10.18.10.0/24 10.18.11.0/24 10.18.12.0/24"
  "ritdu-dcd-eu2.public_subs"      = "10.18.15.0/24 10.18.16.0/24 10.18.17.0/24"
  "ritdu-dcd-eu2.region"           = "eu-west-1"
  "ritdu-dcd-eu2.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-dcd-eu2.account_id"       = "520152236921"

  # sdc
  # cube-sdc
  "cube-sdc-eu1.cidr"             = "10.19.0.0/19"
  "cube-sdc-eu1.single_natgw"     = "true"
  "cube-sdc-eu1.private_subs"     = "10.19.0.0/24 10.19.1.0/24 10.19.2.0/24"
  "cube-sdc-eu1.database_subs"    = "10.19.5.0/24 10.19.6.0/24 10.19.7.0/24"
  "cube-sdc-eu1.elasticache_subs" = "10.19.10.0/24 10.19.11.0/24 10.19.19.0/24"
  "cube-sdc-eu1.public_subs"      = "10.19.15.0/24 10.19.16.0/24 10.19.17.0/24"
  "cube-sdc-eu1.region"           = "eu-west-1"
  "cube-sdc-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "cube-sdc-eu1.account_id"       = "013389100338"

  # unused 2
  # ritdu-unused-2
  "ritdu-unused2-eu1.cidr"             = "10.20.0.0/19"
  "ritdu-unused2-eu1.single_natgw"     = "true"
  "ritdu-unused2-eu1.private_subs"     = "10.20.0.0/24 10.20.1.0/24 10.20.2.0/24"
  "ritdu-unused2-eu1.database_subs"    = "10.20.5.0/24 10.20.6.0/24 10.20.7.0/24"
  "ritdu-unused2-eu1.elasticache_subs" = "10.20.10.0/24 10.20.11.0/24 10.20.19.0/24"
  "ritdu-unused2-eu1.public_subs"      = "10.20.15.0/24 10.20.16.0/24 10.20.17.0/24"
  "ritdu-unused2-eu1.region"           = "eu-west-1"
  "ritdu-unused2-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-unused2-eu1.account_id"       = "000000000002"

  # hex
  # ritdu-hex
  "ritdu-hex-eu1.cidr"             = "10.21.0.0/19"
  "ritdu-hex-eu1.single_natgw"     = "true"
  "ritdu-hex-eu1.private_subs"     = "10.21.0.0/24 10.21.1.0/24 10.21.2.0/24"
  "ritdu-hex-eu1.database_subs"    = "10.21.5.0/24 10.21.6.0/24 10.21.7.0/24"
  "ritdu-hex-eu1.elasticache_subs" = "10.21.10.0/24 10.21.11.0/24 10.21.19.0/24"
  "ritdu-hex-eu1.public_subs"      = "10.21.15.0/24 10.21.16.0/24 10.21.17.0/24"
  "ritdu-hex-eu1.region"           = "eu-west-1"
  "ritdu-hex-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-hex-eu1.account_id"       = "592990123379"

  # unused 1
  # ritdu-unused 1
  "ritdu-unused-eu1.cidr"             = "10.22.0.0/19"
  "ritdu-unused-eu1.single_natgw"     = "true"
  "ritdu-unused-eu1.private_subs"     = "10.22.0.0/24 10.22.1.0/24 10.22.2.0/24"
  "ritdu-unused-eu1.database_subs"    = "10.22.5.0/24 10.22.6.0/24 10.22.7.0/24"
  "ritdu-unused-eu1.elasticache_subs" = "10.22.10.0/24 10.22.11.0/24 10.22.12.0/24"
  "ritdu-unused-eu1.public_subs"      = "10.22.15.0/24 10.22.16.0/24 10.22.17.0/24"
  "ritdu-unused-eu1.region"           = "eu-west-1"
  "ritdu-unused-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-unused-eu1.account_id"       = "000000000001"

  # meta
  # ritdu-meta
  "ritdu-meta-eu1.cidr"             = "10.23.0.0/19"
  "ritdu-meta-eu1.single_natgw"     = "true"
  "ritdu-meta-eu1.private_subs"     = "10.23.0.0/24 10.23.1.0/24 10.23.2.0/24"
  "ritdu-meta-eu1.database_subs"    = "10.23.5.0/24 10.23.6.0/24 10.23.7.0/24"
  "ritdu-meta-eu1.elasticache_subs" = "10.23.10.0/24 10.23.11.0/24 10.23.19.0/24"
  "ritdu-meta-eu1.public_subs"      = "10.23.15.0/24 10.23.16.0/24 10.23.17.0/24"
  "ritdu-meta-eu1.region"           = "eu-west-1"
  "ritdu-meta-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-meta-eu1.account_id"       = "132631306742"

  # bi
  # ritdu-bi
  "ritdu-bi-eu1.cidr"             = "10.24.0.0/19"
  "ritdu-bi-eu1.single_natgw"     = "true"
  "ritdu-bi-eu1.private_subs"     = "10.24.0.0/24 10.24.1.0/24 10.24.2.0/24"
  "ritdu-bi-eu1.database_subs"    = "10.24.5.0/24 10.24.6.0/24 10.24.7.0/24"
  "ritdu-bi-eu1.elasticache_subs" = "10.24.10.0/24 10.24.11.0/24 10.24.19.0/24"
  "ritdu-bi-eu1.public_subs"      = "10.24.15.0/24 10.24.16.0/24 10.24.17.0/24"
  "ritdu-bi-eu1.region"           = "eu-west-1"
  "ritdu-bi-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-bi-eu1.account_id"       = "981242785456"

  # mkt
  # ritdu-mkt
  "ritdu-mkt-eu1.cidr"             = "10.25.0.0/19"
  "ritdu-mkt-eu1.single_natgw"     = "true"
  "ritdu-mkt-eu1.private_subs"     = "10.25.0.0/24 10.25.1.0/24 10.25.2.0/24"
  "ritdu-mkt-eu1.database_subs"    = "10.25.5.0/24 10.25.6.0/24 10.25.7.0/24"
  "ritdu-mkt-eu1.elasticache_subs" = "10.25.10.0/24 10.25.11.0/24 10.25.19.0/24"
  "ritdu-mkt-eu1.public_subs"      = "10.25.15.0/24 10.25.16.0/24 10.25.17.0/24"
  "ritdu-mkt-eu1.region"           = "eu-west-1"
  "ritdu-mkt-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-mkt-eu1.account_id"       = "032310891895"

  # ecom
  # ritdu-ecom
  "ritdu-ecom-eu1.cidr"             = "10.26.0.0/19"
  "ritdu-ecom-eu1.single_natgw"     = "true"
  "ritdu-ecom-eu1.private_subs"     = "10.26.0.0/24 10.26.1.0/24 10.26.2.0/24"
  "ritdu-ecom-eu1.database_subs"    = "10.26.5.0/24 10.26.6.0/24 10.26.7.0/24"
  "ritdu-ecom-eu1.elasticache_subs" = "10.26.10.0/24 10.26.11.0/24 10.26.19.0/24"
  "ritdu-ecom-eu1.public_subs"      = "10.26.15.0/24 10.26.16.0/24 10.26.17.0/24"
  "ritdu-ecom-eu1.region"           = "eu-west-1"
  "ritdu-ecom-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-ecom-eu1.account_id"       = "102891362269"

  # imo
  # rmn-imo
  "rmn-imo-eu1.cidr"             = "10.27.0.0/19"
  "rmn-imo-eu1.single_natgw"     = "true"
  "rmn-imo-eu1.private_subs"     = "10.27.0.0/24 10.27.1.0/24 10.27.2.0/24"
  "rmn-imo-eu1.database_subs"    = "10.27.5.0/24 10.27.6.0/24 10.27.7.0/24"
  "rmn-imo-eu1.elasticache_subs" = "10.27.10.0/24 10.27.11.0/24 10.27.19.0/24"
  "rmn-imo-eu1.public_subs"      = "10.27.15.0/24 10.27.16.0/24 10.27.17.0/24"
  "rmn-imo-eu1.region"           = "eu-central-1"
  "rmn-imo-eu1.azs"              = "eu-central-1a eu-central-1b eu-central-1c"
  "rmn-imo-eu1.account_id"       = "637234805497"

  # vapor
  # ritdu-vapor
  "ritdu-vapor-eu1.cidr"             = "10.28.0.0/19"
  "ritdu-vapor-eu1.single_natgw"     = "true"
  "ritdu-vapor-eu1.private_subs"     = "10.28.0.0/24 10.28.1.0/24 10.28.2.0/24"
  "ritdu-vapor-eu1.database_subs"    = "10.28.5.0/24 10.28.6.0/24 10.28.7.0/24"
  "ritdu-vapor-eu1.elasticache_subs" = "10.28.10.0/24 10.28.11.0/24 10.28.19.0/24"
  "ritdu-vapor-eu1.public_subs"      = "10.28.15.0/24 10.28.16.0/24 10.28.17.0/24"
  "ritdu-vapor-eu1.region"           = "eu-west-1"
  "ritdu-vapor-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-vapor-eu1.account_id"       = "374141200047"

  # cds
  # ritdu-cds
  "ritdu-cds-eu1.cidr"             = "10.29.0.0/19"
  "ritdu-cds-eu1.single_natgw"     = "true"
  "ritdu-cds-eu1.private_subs"     = "10.29.0.0/24 10.29.1.0/24 10.29.2.0/24"
  "ritdu-cds-eu1.database_subs"    = "10.29.5.0/24 10.29.6.0/24 10.29.7.0/24"
  "ritdu-cds-eu1.elasticache_subs" = "10.29.10.0/24 10.29.11.0/24 10.29.19.0/24"
  "ritdu-cds-eu1.public_subs"      = "10.29.15.0/24 10.29.16.0/24 10.29.17.0/24"
  "ritdu-cds-eu1.region"           = "eu-west-1"
  "ritdu-cds-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-cds-eu1.account_id"       = "838756042015"


  # sol
  # ritdu-sol-eu1
  "ritdu-sol-eu1.cidr"             = "10.30.0.0/19"
  "ritdu-sol-eu1.single_natgw"     = "true"
  "ritdu-sol-eu1.private_subs"     = "10.30.0.0/24 10.30.1.0/24 10.30.2.0/24"
  "ritdu-sol-eu1.database_subs"    = "10.30.5.0/24 10.30.6.0/24 10.30.7.0/24"
  "ritdu-sol-eu1.elasticache_subs" = "10.30.10.0/24 10.30.11.0/24 10.30.19.0/24"
  "ritdu-sol-eu1.public_subs"      = "10.30.15.0/24 10.30.16.0/24 10.30.17.0/24"
  "ritdu-sol-eu1.region"           = "eu-west-1"
  "ritdu-sol-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-sol-eu1.account_id"       = "038858594630"

  # logs
  # ritdu-logs-eu1
  "ritdu-logs-eu1.cidr"             = "10.31.0.0/19"
  "ritdu-logs-eu1.single_natgw"     = "true"
  "ritdu-logs-eu1.private_subs"     = "10.31.0.0/24 10.31.1.0/24 10.31.2.0/24"
  "ritdu-logs-eu1.database_subs"    = "10.31.5.0/24 10.31.6.0/24 10.31.7.0/24"
  "ritdu-logs-eu1.elasticache_subs" = "10.31.10.0/24 10.31.11.0/24 10.31.19.0/24"
  "ritdu-logs-eu1.public_subs"      = "10.31.15.0/24 10.31.16.0/24 10.31.17.0/24"
  "ritdu-logs-eu1.region"           = "eu-west-1"
  "ritdu-logs-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-logs-eu1.account_id"       = "767397910791"

  # ritdu-ias
  # ritdu-ias-eu1
  "ritdu-ias-eu1.cidr"             = "10.32.0.0/19"
  "ritdu-ias-eu1.single_natgw"     = "true"
  "ritdu-ias-eu1.private_subs"     = "10.32.0.0/24 10.32.1.0/24 10.32.2.0/24"
  "ritdu-ias-eu1.database_subs"    = "10.32.5.0/24 10.32.6.0/24 10.32.7.0/24"
  "ritdu-ias-eu1.elasticache_subs" = "10.32.10.0/24 10.32.11.0/24 10.32.19.0/24"
  "ritdu-ias-eu1.public_subs"      = "10.32.15.0/24 10.32.16.0/24 10.32.17.0/24"
  "ritdu-ias-eu1.region"           = "eu-central-1"
  "ritdu-ias-eu1.azs"              = "eu-central-1a eu-central-1b eu-central-1c"
  "ritdu-ias-eu1.account_id"       = "337909768645"

  # ritdu-rsmg
  # ritdu-rsmg-eu1
  "ritdu-rsmg-eu1.cidr"             = "10.33.0.0/19"
  "ritdu-rsmg-eu1.single_natgw"     = "true"
  "ritdu-rsmg-eu1.private_subs"     = "10.33.0.0/24 10.33.1.0/24 10.33.2.0/24"
  "ritdu-rsmg-eu1.database_subs"    = "10.33.5.0/24 10.33.6.0/24 10.33.7.0/24"
  "ritdu-rsmg-eu1.elasticache_subs" = "10.33.10.0/24 10.33.11.0/24 10.33.19.0/24"
  "ritdu-rsmg-eu1.public_subs"      = "10.33.15.0/24 10.33.16.0/24 10.33.17.0/24"
  "ritdu-rsmg-eu1.region"           = "eu-west-1"
  "ritdu-rsmg-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-rsmg-eu1.account_id"       = "975050125252"

  # ritdu-ias
  # ritdu-rias-mdb-eu1: occupies the whole VPC CIDR 10.44.0.0/16
  "ritdu-rias-mdb-eu1.cidr"             = "10.44.96.0/19"
  "ritdu-rias-mdb-eu1.single_natgw"     = "true"
  "ritdu-rias-mdb-eu1.private_subs"     = "10.44.96.0/24 10.44.97.0/24 10.44.98.0/24"
  "ritdu-rias-mdb-eu1.database_subs"    = "10.44.101.0/24 10.44.102.0/24 10.44.103.0/24"
  "ritdu-rias-mdb-eu1.elasticache_subs" = "10.44.106.0/24 10.44.107.0/24 10.44.108.0/24"
  "ritdu-rias-mdb-eu1.public_subs"      = "10.44.111.0/24 10.44.112.0/24 10.44.113.0/24"
  "ritdu-rias-mdb-eu1.region"           = "eu-central-1"
  "ritdu-rias-mdb-eu1.azs"              = "eu-central-1a eu-central-1b eu-central-1c"
  "ritdu-rias-mdb-eu1.account_id"       = "941377142040"
}
