# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #
# 💥                                                            💥 #
# 💥 Do not edit this file as it will be overwritten!           💥 #
# 💥                                                            💥 #
# 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 💥 #



ns_env_name = "qa"

vpcs = {
  # we unfortunately can not mix types, but will be fixed in 0.12 (see: https://github.com/hashicorp/terraform/issues/14322)

  # base/core account
  # rimu
  "rimu.cidr"             = "172.16.32.0/19"
  "rimu.single_natgw"     = "true"
  "rimu.private_subs"     = "172.16.32.0/24 172.16.33.0/24 172.16.34.0/24"
  "rimu.database_subs"    = "172.16.37.0/24 172.16.38.0/24 172.16.39.0/24"
  "rimu.elasticache_subs" = "172.16.42.0/24 172.16.43.0/24 172.16.44.0/24"
  "rimu.public_subs"      = "172.16.47.0/24 172.16.48.0/24 172.16.49.0/24"
  "rimu.region"           = "eu-west-1"
  "rimu.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "rimu.account_id"       = "135132174985"

  # payeer account
  # ritdu-main
  "ritdu-main.cidr"             = "10.11.32.0/19"
  "ritdu-main.single_natgw"     = "true"
  "ritdu-main.private_subs"     = "10.11.32.0/24 10.11.33.0/24 10.11.34.0/24"
  "ritdu-main.database_subs"    = "10.11.37.0/24 10.11.38.0/24 10.11.39.0/24"
  "ritdu-main.elasticache_subs" = "10.11.42.0/24 10.11.43.0/24 10.11.44.0/24"
  "ritdu-main.public_subs"      = "10.11.47.0/24 10.11.48.0/24 10.11.49.0/24"
  "ritdu-main.region"           = "eu-west-1"
  "ritdu-main.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-main.account_id"       = "953455652261"

  # jobs
  # ritdu-jobs
  "ritdu-jobs-af1.cidr"             = "10.12.32.0/19"
  "ritdu-jobs-af1.single_natgw"     = "true"
  "ritdu-jobs-af1.private_subs"     = "10.12.32.0/24 10.12.33.0/24 10.12.34.0/24"
  "ritdu-jobs-af1.database_subs"    = "10.12.37.0/24 10.12.38.0/24 10.12.39.0/24"
  "ritdu-jobs-af1.elasticache_subs" = "10.12.42.0/24 10.12.43.0/24 10.12.44.0/24"
  "ritdu-jobs-af1.public_subs"      = "10.12.47.0/24 10.12.48.0/24 10.12.49.0/24"
  "ritdu-jobs-af1.region"           = "eu-west-1"
  "ritdu-jobs-af1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-jobs-af1.account_id"       = "471953789682"

  # sec 1
  # ritdu-sec 1
  "ritdu-sec-eu1.cidr"             = "10.13.32.0/19"
  "ritdu-sec-eu1.single_natgw"     = "true"
  "ritdu-sec-eu1.private_subs"     = "10.13.32.0/24 10.13.33.0/24 10.13.34.0/24"
  "ritdu-sec-eu1.database_subs"    = "10.13.37.0/24 10.13.38.0/24 10.13.39.0/24"
  "ritdu-sec-eu1.elasticache_subs" = "10.13.42.0/24 10.13.43.0/24 10.13.44.0/24"
  "ritdu-sec-eu1.public_subs"      = "10.13.47.0/24 10.13.48.0/24 10.13.49.0/24"
  "ritdu-sec-eu1.region"           = "eu-west-1"
  "ritdu-sec-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-sec-eu1.account_id"       = "636025426721"

  # horizon
  # roam-horizon
  "roam-horizon-af1.cidr"             = "10.14.32.0/19"
  "roam-horizon-af1.single_natgw"     = "true"
  "roam-horizon-af1.private_subs"     = "10.14.32.0/24 10.14.33.0/24 10.14.34.0/24"
  "roam-horizon-af1.database_subs"    = "10.14.37.0/24 10.14.38.0/24 10.14.39.0/24"
  "roam-horizon-af1.elasticache_subs" = "10.14.42.0/24 10.14.43.0/24 10.14.44.0/24"
  "roam-horizon-af1.public_subs"      = "10.14.47.0/24 10.14.48.0/24 10.14.49.0/24"
  "roam-horizon-af1.region"           = "eu-west-1"
  "roam-horizon-af1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "roam-horizon-af1.account_id"       = "947872912714"

  # bus 1
  # ritdu-dcd
  "ritdu-dcd.cidr"             = "10.15.32.0/19"
  "ritdu-dcd.single_natgw"     = "true"
  "ritdu-dcd.private_subs"     = "10.15.32.0/24 10.15.33.0/24 10.15.34.0/24"
  "ritdu-dcd.database_subs"    = "10.15.37.0/24 10.15.38.0/24 10.15.39.0/24"
  "ritdu-dcd.elasticache_subs" = "10.15.42.0/24 10.15.43.0/24 10.15.44.0/24"
  "ritdu-dcd.public_subs"      = "10.15.47.0/24 10.15.48.0/24 10.15.49.0/24"
  "ritdu-dcd.region"           = "eu-west-1"
  "ritdu-dcd.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-dcd.account_id"       = "634401859868"

  # prop
  # rimu-prop
  "rimu-prop-vnm.cidr"             = "10.16.32.0/19"
  "rimu-prop-vnm.single_natgw"     = "true"
  "rimu-prop-vnm.private_subs"     = "10.16.32.0/24 10.16.33.0/24 10.16.34.0/24"
  "rimu-prop-vnm.database_subs"    = "10.16.37.0/24 10.16.38.0/24 10.16.39.0/24"
  "rimu-prop-vnm.elasticache_subs" = "10.16.42.0/24 10.16.43.0/24 10.16.44.0/24"
  "rimu-prop-vnm.public_subs"      = "10.16.47.0/24 10.16.48.0/24 10.16.49.0/24"
  "rimu-prop-vnm.region"           = "eu-west-1"
  "rimu-prop-vnm.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "rimu-prop-vnm.account_id"       = "348539006591"

  # testing/pe
  # ritdu-pe
  "ritdu-pe-eu1.cidr"             = "10.17.32.0/19"
  "ritdu-pe-eu1.single_natgw"     = "true"
  "ritdu-pe-eu1.private_subs"     = "10.17.32.0/24 10.17.33.0/24 10.17.34.0/24"
  "ritdu-pe-eu1.database_subs"    = "10.17.37.0/24 10.17.38.0/24 10.17.39.0/24"
  "ritdu-pe-eu1.elasticache_subs" = "10.17.42.0/24 10.17.43.0/24 10.17.44.0/24"
  "ritdu-pe-eu1.public_subs"      = "10.17.47.0/24 10.17.48.0/24 10.17.49.0/24"
  "ritdu-pe-eu1.region"           = "eu-west-1"
  "ritdu-pe-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-pe-eu1.account_id"       = "025015820777"

  # bus 2
  # ritdu-dcd
  "ritdu-dcd-eu2.cidr"             = "10.18.32.0/19"
  "ritdu-dcd-eu2.single_natgw"     = "true"
  "ritdu-dcd-eu2.private_subs"     = "10.18.32.0/24 10.18.33.0/24 10.18.34.0/24"
  "ritdu-dcd-eu2.database_subs"    = "10.18.37.0/24 10.18.38.0/24 10.18.39.0/24"
  "ritdu-dcd-eu2.elasticache_subs" = "10.18.42.0/24 10.18.43.0/24 10.18.44.0/24"
  "ritdu-dcd-eu2.public_subs"      = "10.18.47.0/24 10.18.48.0/24 10.18.49.0/24"
  "ritdu-dcd-eu2.region"           = "eu-west-1"
  "ritdu-dcd-eu2.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-dcd-eu2.account_id"       = "520152236921"

  # sdc
  # cube-sdc
  "cube-sdc-eu1.cidr"             = "10.19.32.0/19"
  "cube-sdc-eu1.single_natgw"     = "true"
  "cube-sdc-eu1.private_subs"     = "10.19.32.0/24 10.19.33.0/24 10.19.34.0/24"
  "cube-sdc-eu1.database_subs"    = "10.19.37.0/24 10.19.38.0/24 10.19.39.0/24"
  "cube-sdc-eu1.elasticache_subs" = "10.19.42.0/24 10.19.43.0/24 10.19.44.0/24"
  "cube-sdc-eu1.public_subs"      = "10.19.47.0/24 10.19.48.0/24 10.19.49.0/24"
  "cube-sdc-eu1.region"           = "eu-west-1"
  "cube-sdc-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "cube-sdc-eu1.account_id"       = "013389100338"

  # unused 2
  # ritdu-unused-2
  "ritdu-unused2-eu1.cidr"             = "10.20.32.0/19"
  "ritdu-unused2-eu1.single_natgw"     = "true"
  "ritdu-unused2-eu1.private_subs"     = "10.20.32.0/24 10.20.33.0/24 10.20.34.0/24"
  "ritdu-unused2-eu1.database_subs"    = "10.20.37.0/24 10.20.38.0/24 10.20.39.0/24"
  "ritdu-unused2-eu1.elasticache_subs" = "10.20.42.0/24 10.20.43.0/24 10.20.44.0/24"
  "ritdu-unused2-eu1.public_subs"      = "10.20.47.0/24 10.20.48.0/24 10.20.49.0/24"
  "ritdu-unused2-eu1.region"           = "eu-west-1"
  "ritdu-unused2-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-unused2-eu1.account_id"       = "000000000002"

  # hex
  # ritdu-hex
  "ritdu-hex-eu1.cidr"             = "10.21.32.0/19"
  "ritdu-hex-eu1.single_natgw"     = "true"
  "ritdu-hex-eu1.private_subs"     = "10.21.32.0/24 10.21.33.0/24 10.21.34.0/24"
  "ritdu-hex-eu1.database_subs"    = "10.21.37.0/24 10.21.38.0/24 10.21.39.0/24"
  "ritdu-hex-eu1.elasticache_subs" = "10.21.42.0/24 10.21.43.0/24 10.21.44.0/24"
  "ritdu-hex-eu1.public_subs"      = "10.21.47.0/24 10.21.48.0/24 10.21.49.0/24"
  "ritdu-hex-eu1.region"           = "eu-west-1"
  "ritdu-hex-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-hex-eu1.account_id"       = "592990123379"

  # unused 1
  # ritdu-unused 1
  "ritdu-unused-eu1.cidr"             = "10.22.32.0/19"
  "ritdu-unused-eu1.single_natgw"     = "true"
  "ritdu-unused-eu1.private_subs"     = "10.22.32.0/24 10.22.33.0/24 10.22.34.0/24"
  "ritdu-unused-eu1.database_subs"    = "10.22.37.0/24 10.22.38.0/24 10.22.39.0/24"
  "ritdu-unused-eu1.elasticache_subs" = "10.22.42.0/24 10.22.43.0/24 10.22.44.0/24"
  "ritdu-unused-eu1.public_subs"      = "10.22.47.0/24 10.22.48.0/24 10.22.49.0/24"
  "ritdu-unused-eu1.region"           = "eu-west-1"
  "ritdu-unused-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-unused-eu1.account_id"       = "000000000001"

  # meta
  # ritdu-meta
  "ritdu-meta-eu1.cidr"             = "10.23.32.0/19"
  "ritdu-meta-eu1.single_natgw"     = "true"
  "ritdu-meta-eu1.private_subs"     = "10.23.32.0/24 10.23.33.0/24 10.23.34.0/24"
  "ritdu-meta-eu1.database_subs"    = "10.23.37.0/24 10.23.38.0/24 10.23.39.0/24"
  "ritdu-meta-eu1.elasticache_subs" = "10.23.42.0/24 10.23.43.0/24 10.23.44.0/24"
  "ritdu-meta-eu1.public_subs"      = "10.23.47.0/24 10.23.48.0/24 10.23.49.0/24"
  "ritdu-meta-eu1.region"           = "eu-west-1"
  "ritdu-meta-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-meta-eu1.account_id"       = "132631306742"

  # bi
  # ritdu-bi
  "ritdu-bi-eu1.cidr"             = "10.24.32.0/19"
  "ritdu-bi-eu1.single_natgw"     = "true"
  "ritdu-bi-eu1.private_subs"     = "10.24.32.0/24 10.24.33.0/24 10.24.34.0/24"
  "ritdu-bi-eu1.database_subs"    = "10.24.37.0/24 10.24.38.0/24 10.24.39.0/24"
  "ritdu-bi-eu1.elasticache_subs" = "10.24.42.0/24 10.24.43.0/24 10.24.44.0/24"
  "ritdu-bi-eu1.public_subs"      = "10.24.47.0/24 10.24.48.0/24 10.24.49.0/24"
  "ritdu-bi-eu1.region"           = "eu-west-1"
  "ritdu-bi-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-bi-eu1.account_id"       = "981242785456"

  # mkt
  # ritdu-mkt
  "ritdu-mkt-eu1.cidr"             = "10.25.32.0/19"
  "ritdu-mkt-eu1.single_natgw"     = "true"
  "ritdu-mkt-eu1.private_subs"     = "10.25.32.0/24 10.25.33.0/24 10.25.34.0/24"
  "ritdu-mkt-eu1.database_subs"    = "10.25.37.0/24 10.25.38.0/24 10.25.39.0/24"
  "ritdu-mkt-eu1.elasticache_subs" = "10.25.42.0/24 10.25.43.0/24 10.25.44.0/24"
  "ritdu-mkt-eu1.public_subs"      = "10.25.47.0/24 10.25.48.0/24 10.25.49.0/24"
  "ritdu-mkt-eu1.region"           = "eu-west-1"
  "ritdu-mkt-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-mkt-eu1.account_id"       = "032310891895"

  # ecom
  # ritdu-ecom
  "ritdu-ecom-eu1.cidr"             = "10.26.32.0/19"
  "ritdu-ecom-eu1.single_natgw"     = "true"
  "ritdu-ecom-eu1.private_subs"     = "10.26.32.0/24 10.26.33.0/24 10.26.34.0/24"
  "ritdu-ecom-eu1.database_subs"    = "10.26.37.0/24 10.26.38.0/24 10.26.39.0/24"
  "ritdu-ecom-eu1.elasticache_subs" = "10.26.42.0/24 10.26.43.0/24 10.26.44.0/24"
  "ritdu-ecom-eu1.public_subs"      = "10.26.47.0/24 10.26.48.0/24 10.26.49.0/24"
  "ritdu-ecom-eu1.region"           = "eu-west-1"
  "ritdu-ecom-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-ecom-eu1.account_id"       = "102891362269"

  # imo
  # rmn-imo
  "rmn-imo-eu1.cidr"             = "10.27.32.0/19"
  "rmn-imo-eu1.single_natgw"     = "true"
  "rmn-imo-eu1.private_subs"     = "10.27.32.0/24 10.27.33.0/24 10.27.34.0/24"
  "rmn-imo-eu1.database_subs"    = "10.27.37.0/24 10.27.38.0/24 10.27.39.0/24"
  "rmn-imo-eu1.elasticache_subs" = "10.27.42.0/24 10.27.43.0/24 10.27.44.0/24"
  "rmn-imo-eu1.public_subs"      = "10.27.47.0/24 10.27.48.0/24 10.27.49.0/24"
  "rmn-imo-eu1.region"           = "eu-central-1"
  "rmn-imo-eu1.azs"              = "eu-central-1a eu-central-1b eu-central-1c"
  "rmn-imo-eu1.account_id"       = "637234805497"

  # vapor
  # ritdu-vapor
  "ritdu-vapor-eu1.cidr"             = "10.28.32.0/19"
  "ritdu-vapor-eu1.single_natgw"     = "true"
  "ritdu-vapor-eu1.private_subs"     = "10.28.32.0/24 10.28.33.0/24 10.28.34.0/24"
  "ritdu-vapor-eu1.database_subs"    = "10.28.37.0/24 10.28.38.0/24 10.28.39.0/24"
  "ritdu-vapor-eu1.elasticache_subs" = "10.28.42.0/24 10.28.43.0/24 10.28.44.0/24"
  "ritdu-vapor-eu1.public_subs"      = "10.28.47.0/24 10.28.48.0/24 10.28.49.0/24"
  "ritdu-vapor-eu1.region"           = "eu-west-1"
  "ritdu-vapor-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-vapor-eu1.account_id"       = "374141200047"

  # cds
  # ritdu-cds
  "ritdu-cds-eu1.cidr"             = "10.29.32.0/19"
  "ritdu-cds-eu1.single_natgw"     = "true"
  "ritdu-cds-eu1.private_subs"     = "10.29.32.0/24 10.29.33.0/24 10.29.34.0/24"
  "ritdu-cds-eu1.database_subs"    = "10.29.37.0/24 10.29.38.0/24 10.29.39.0/24"
  "ritdu-cds-eu1.elasticache_subs" = "10.29.42.0/24 10.29.43.0/24 10.29.44.0/24"
  "ritdu-cds-eu1.public_subs"      = "10.29.47.0/24 10.29.48.0/24 10.29.49.0/24"
  "ritdu-cds-eu1.region"           = "eu-west-1"
  "ritdu-cds-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-cds-eu1.account_id"       = "838756042015"

  # sol
  # ritdu-sol
  "ritdu-sol-eu1.cidr"             = "10.30.32.0/19"
  "ritdu-sol-eu1.single_natgw"     = "true"
  "ritdu-sol-eu1.private_subs"     = "10.30.32.0/24 10.30.33.0/24 10.30.34.0/24"
  "ritdu-sol-eu1.database_subs"    = "10.30.37.0/24 10.30.38.0/24 10.30.39.0/24"
  "ritdu-sol-eu1.elasticache_subs" = "10.30.42.0/24 10.30.43.0/24 10.30.44.0/24"
  "ritdu-sol-eu1.public_subs"      = "10.30.47.0/24 10.30.48.0/24 10.30.49.0/24"
  "ritdu-sol-eu1.region"           = "eu-west-1"
  "ritdu-sol-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-sol-eu1.account_id"       = "038858594630"

  # logs
  # ritdu-logs-eu1
  "ritdu-logs-eu1.cidr"             = "10.31.32.0/19"
  "ritdu-logs-eu1.single_natgw"     = "true"
  "ritdu-logs-eu1.private_subs"     = "10.31.32.0/24 10.31.33.0/24 10.31.34.0/24"
  "ritdu-logs-eu1.database_subs"    = "10.31.37.0/24 10.31.38.0/24 10.31.39.0/24"
  "ritdu-logs-eu1.elasticache_subs" = "10.31.42.0/24 10.31.43.0/24 10.31.44.0/24"
  "ritdu-logs-eu1.public_subs"      = "10.31.47.0/24 10.31.48.0/24 10.31.49.0/24"
  "ritdu-logs-eu1.region"           = "eu-west-1"
  "ritdu-logs-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-logs-eu1.account_id"       = "767397910791"

  # unused 3
  # ritdu-unused-3
  "ritdu-unused3-eu1.cidr"             = "10.32.32.0/19"
  "ritdu-unused3-eu1.single_natgw"     = "true"
  "ritdu-unused3-eu1.private_subs"     = "10.32.32.0/24 10.32.33.0/24 10.32.34.0/24"
  "ritdu-unused3-eu1.database_subs"    = "10.32.37.0/24 10.32.38.0/24 10.32.39.0/24"
  "ritdu-unused3-eu1.elasticache_subs" = "10.32.42.0/24 10.32.43.0/24 10.32.44.0/24"
  "ritdu-unused3-eu1.public_subs"      = "10.32.47.0/24 10.32.48.0/24 10.32.49.0/24"
  "ritdu-unused3-eu1.region"           = "eu-west-1"
  "ritdu-unused3-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-unused3-eu1.account_id"       = "000000000003"

  # ritdu-rsmg
  # ritdu-rsmg-eu1
  "ritdu-rsmg-eu1.cidr"             = "10.33.32.0/19"
  "ritdu-rsmg-eu1.single_natgw"     = "true"
  "ritdu-rsmg-eu1.private_subs"     = "10.33.32.0/24 10.33.33.0/24 10.33.34.0/24"
  "ritdu-rsmg-eu1.database_subs"    = "10.33.37.0/24 10.33.38.0/24 10.33.39.0/24"
  "ritdu-rsmg-eu1.elasticache_subs" = "10.33.42.0/24 10.33.43.0/24 10.33.44.0/24"
  "ritdu-rsmg-eu1.public_subs"      = "10.33.47.0/24 10.33.48.0/24 10.33.49.0/24"
  "ritdu-rsmg-eu1.region"           = "eu-west-1"
  "ritdu-rsmg-eu1.azs"              = "eu-west-1a eu-west-1b eu-west-1c"
  "ritdu-rsmg-eu1.account_id"       = "975050125252"

  # ritdu-ias
  # rias-mdb-eu1: occupies the whole CIDR 10.200.0.0/16
  "rias-mdb-eu1.cidr"             = "10.200.32.0/19"
  "rias-mdb-eu1.single_natgw"     = "true"
  "rias-mdb-eu1.private_subs"     = "10.200.32.0/24 10.200.33.0/24 10.200.34.0/24"
  "rias-mdb-eu1.database_subs"    = "10.200.37.0/24 10.200.38.0/24 10.200.39.0/24"
  "rias-mdb-eu1.elasticache_subs" = "10.200.42.0/24 10.200.43.0/24 10.200.44.0/24"
  "rias-mdb-eu1.public_subs"      = "10.200.47.0/24 10.200.48.0/24 10.200.49.0/24"
  "rias-mdb-eu1.region"           = "eu-central-1"
  "rias-mdb-eu1.azs"              = "eu-central-1a eu-central-1b eu-central-1c"
  "rias-mdb-eu1.account_id"       = "321298294662"
}
